### ISSUE TITLE
Seller Dashboard / Email Update

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/FileShop#6]
Seller Dashboard contains statistics like number of products downloaded / viewed / Total bitcoin amount received etc.  It also contains the link to trigger withdraw the received income. Link to seller dashboard (unique per product) is sent to seller email address. 

Seller email address is captured on Page2 after seller has done product upload. Seller should also receive notifications of successful sale so that we can view dashboard thereafter.

**Comment by cnohall** [comment]
Email update is already functioning:
![image](https://user-images.githubusercontent.com/36883813/127045246-e86a06a2-3595-4fa4-a4ae-dda50b0c213e.png)

The typo `here here` has already been fixed.

Both emails are quite generic:
![image](https://user-images.githubusercontent.com/36883813/127045567-aaffd60d-6fb0-4509-b7d3-8395f0fafd89.png)

Perhaps the UI for both the emails can be slightly improved? This might give an even better impression.

**Comment by vv181** [comment]
> Perhaps the UI for both the emails can be slightly improved? This might give an even better impression.

I think the UI for the email should match the overall look of the site. I'd like to work on that and maybe improve the whole UI of the website. Does anyone have any reference about how the site/email want to look like?
